version: '3.4'

services:
  db:
    image: apiresaspnetdb
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    build:
      context: .
      dockerfile: db/Dockerfile
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: docker
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      MYSQL_DATABASE: aspnetdb
    ports:
      - 3308:3306
    networks:
      - aspnet-network
      
  apirestaspnet:
    image: apirestaspnet
    build:
      context: .
      dockerfile: ApiRestASPNET/Dockerfile
    environment:
      TZ: America/Sao_Paulo
      ASPNETCORE_ENVIRONMENT: Production
    ports:
       - 44300:80
    depends_on:
      - db
    networks:
      - aspnet-network
networks:
  aspnet-network:
    driver: bridge